-- Supabase schema for Shewell
-- Run this in the Supabase SQL editor.

create table if not exists public."user" (
    id bigint generated by default as identity primary key,
    email text not null unique,
    password_hash text not null,
    name text not null,
    phone text not null,
    due_date date
);

create table if not exists public.doctor (
    id bigint generated by default as identity primary key,
    email text not null unique,
    password_hash text not null,
    name text not null,
    specialization text not null,
    experience integer not null,
    phone text not null,
    available_days text not null,
    per_minute_price numeric(10,2) not null default 0
);

create table if not exists public.appointment (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public."user"(id) on delete cascade,
    doctor_id bigint not null references public.doctor(id) on delete cascade,
    date date not null,
    time text not null,
    status text not null default 'scheduled',
    created_at timestamptz not null default now()
);

create table if not exists public.chat_history (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public."user"(id) on delete cascade,
    message text not null,
    response text not null,
    timestamp timestamptz not null default now()
);

create index if not exists idx_appointment_user_id on public.appointment(user_id);
create index if not exists idx_appointment_doctor_id on public.appointment(doctor_id);
create index if not exists idx_chat_history_user_id on public.chat_history(user_id);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public."user" to anon, authenticated;
grant select, insert, update, delete on table public.doctor to anon, authenticated;
grant select, insert, update, delete on table public.appointment to anon, authenticated;
grant select, insert, update, delete on table public.chat_history to anon, authenticated;

-- Optional: seed an admin/doctor record manually from the Supabase dashboard.

-- ==========================================================================
-- Row-Level Security (RLS) — permissive policies for initial testing
-- WARNING: These policies are permissive (USING = true). For production,
-- tighten conditions (e.g. check auth.uid() or restrict to service_role).
-- You can alternatively set the server to use the Supabase `service_role`
-- key so writes bypass RLS (recommended for server-side only keys).
-- ==========================================================================

-- Enable RLS and create broad policies to allow anon/authenticated access
alter table public."user" enable row level security;
create policy "allow_all_on_user" on public."user"
    for all
    to anon, authenticated
    using (true)
    with check (true);

alter table public.doctor enable row level security;
create policy "allow_all_on_doctor" on public.doctor
    for all
    to anon, authenticated
    using (true)
    with check (true);

alter table public.appointment enable row level security;
create policy "allow_all_on_appointment" on public.appointment
    for all
    to anon, authenticated
    using (true)
    with check (true);

alter table public.chat_history enable row level security;
create policy "allow_all_on_chat_history" on public.chat_history
    for all
    to anon, authenticated
    using (true)
    with check (true);

-- End of RLS policies
